use_frameworks!

platform :ios, '8.0'

target 'YBRevealServer_Example' do
  pod 'YBRevealServer', :path => '../'

  target 'YBRevealServer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
